//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_by_Category
    {
        public string CategoryNameCustom { get; set; }
        public string ProductName { get; set; }
        public string QuantityPerUnit { get; set; }
        public Nullable<UnitsInStockEnum> UnitsInStockCustom { get; set; }
        public bool Discontinued { get; set; }
    }
}
