//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Totals_by_Amount
    {
        public Nullable<decimal> SaleAmount { get; set; }
        public int OrderIDCustom { get; set; }
        public string CompanyNameCustom { get; set; }
        public Nullable<System.DateTime> ShippedDateCustom { get; set; }
    }
}
