//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int Id { get; set; }
        public string Species { get; set; }
        public string Discriminator { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string Name { get; set; }
        public string FavoriteToy { get; set; }
    }
}
