// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EntityFrameworkRuler
{
    internal sealed partial class Vsix
    {
        public const string Id = "EntityFrameworkRuler.d1e5b312-e52d-4421-addb-8889510e7944";
        public const string Name = "Entity Framework Ruler";
        public const string Description = @"Adds design-time customization of the EF Core reverse engineered model including property naming, EDMX upgrade support, and more.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Mark Randell";
        public const string Tags = "Entity Framework Core EF Data EntityFramework EntityFrameworkCore EFCore EDMX efruler";
    }
}
