// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EntityFrameworkRuler
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string EntityFrameworkRulerString = "bb8971ac-b841-4110-a51d-6981b05d11d2";
        public static Guid EntityFrameworkRuler = new Guid(EntityFrameworkRulerString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int EditRulesCommand = 0x0100;
        public const int ConvertEdmxToRulesCommand = 0x0200;
    }
}